eslint/eslint-scope

package.json
src/scope-manager.js
src/scope.js

Remove es6-map and es6-weakmap as they are included in node4

Chore: Remove es6-map and es6-weakmap as they are included in node4

---

package.json

Package.json was missing `files` section, which prevents the release.

Chore: Add files section to package.json

---

lib/index.js

This fixes a divergence between the exported API of `eslint-scope` and `escope`. Previously, with `escope`, the following code would return the Scope class:
```js
> require('escope').Scope
[Function: Scope]
```
However, with `eslint-scope` this returns an object that has a key `Scope` in it:
```js
> require('eslint-scope').Scope
{ Scope: [Function: Scope],
GlobalScope: [Function: GlobalScope],
ModuleScope: [Function: ModuleScope],
FunctionExpressionNameScope: [Function: FunctionExpressionNameScope],
CatchScope: [Function: CatchScope],
WithScope: [Function: WithScope],
TDZScope: [Function: TDZScope],
BlockScope: [Function: BlockScope],
SwitchScope: [Function: SwitchScope],
FunctionScope: [Function: FunctionScope],
ForScope: [Function: ForScope],
ClassScope: [Function: ClassScope] }
``` …

Fix: restore previous Scope API export behavior

---

lib/scope.js
tests/es6-default-parameters.js
tests/util/espree.js

Fixes eslint/eslint#9335.
This PR fixes wrong resolutions about the references in default parameters. In the following case:
```js
let a // (A)
function f(x = a) { // This `a` should be resolved to (A), but was resovled to (B).
let a // (B)
}
```
After this PR, the `a` in default parameters is resolved to (A) correctly.
----
This fixing is not ideal.
As the step 27.a of [9.2.12 FunctionDeclarationInstantiation( func, argumentsList )](https://www.ecma-international.org/ecma-262/8.0/#sec-functiondeclarationinstantiation) mentioned, it should make new scope for the function body if the parameters has any default value. However, I guessed that it's a huge breaking change which breaks many ESLint rules. So I kept scope structure and modified the resolution logic.

Fix: wrong resolution about default parameters

---

lib/referencer.js
lib/scope-manager.js
lib/scope.js
lib/variable.js
tests/es6-destructuring-assignments.js
tests/es6-iteration-scope.js

Refs eslint/eslint#10245.
This PR removes `TDZScope` class.
`eslint-scope` package should not make TDZ scopes because this is static analyzer and Temporal Dead Zone is a timing matter.
As results:
- `for-in`/`for-of` statements no longer make TDZ scopes.
- The references in `ForInStatement#right` and `ForOfStatement#right` are in the correct place now.
I confirmed that `eslint` doesn't need any fix for this change (eslint/eslint#10270).

Breaking: remove TDZScope (refs eslint/eslint#10245)

---

lib/scope.js
tests/es6-arrow-function-expression.js

Fix arrow function scope strictness

---

lib/scope.js
tests/es6-arrow-function-expression.js

This reverts commit 2533966faf317df5a3847fab937ba462c16808b8.
The change is causing ESLint to crash with a parsing error on the following code:
```js
console.log(this); z(x => console.log(x, this))
```
```
TypeError: Cannot read property 'length' of undefined
at isStrictScope (/Users/tkatz/code/eslint/node_modules/eslint-scope/lib/scope.js:93:40)
at new Scope (/Users/tkatz/code/eslint/node_modules/eslint-scope/lib/scope.js:254:25)
at new FunctionScope (/Users/tkatz/code/eslint/node_modules/eslint-scope/lib/scope.js:641:9)
at ScopeManager.__nestFunctionScope (/Users/tkatz/code/eslint/node_modules/eslint-scope/lib/scope-manager.js:209:33)
at Referencer.visitFunction (/Users/tkatz/code/eslint/node_modules/eslint-scope/lib/referencer.js:200:27)
at Referencer.ArrowFunctionExpression …
```

Revert "Fix: Arrow function scope strictness (fixes #49) (#50)"

---

lib/scope.js
tests/es6-arrow-function-expression.js

Fixes #49 
This has the original (broken) commit from #50 cherry-picked, and a separate a4ee79e commit fixing the `.length` error from #51.
I found linking (`npm link`) `eslint-scope` into `eslint` and running eslint's unit tests helpful, maybe this could be part of the `eslint-scope`'s CI checks?

Fix: arrow function scope strictness (take 2)

---

.travis.yml
package.json

refs https://github.com/eslint/eslint-scope/pull/53
Now that we've dropped support for Node <8, I think we should also drop support here. I'd like to merge this, merge https://github.com/eslint/eslint-scope/pull/53, and then cut a major release.
~~__Edit:__ @ilyavolodin made me aware that Webpack depends on `eslint-scope` directly, and it appears that they still support Node@6. Maybe this isn't something we want to do yet?~~
This was [discussed by the TSC](https://github.com/eslint/eslint-scope/pull/54#issuecomment-513060862), who resolved to accept this.

Breaking: drop support for Node v6

---

.eslintignore
.eslintrc.js
.eslintrc.yml
Makefile.js
lib/index.js
lib/referencer.js
lib/scope.js
package.json
tests/.eslintrc.yml
tests/es6-block-scope.js
tests/es6-default-parameters.js
tests/es6-destructuring-assignments.js
tests/es6-export.js
tests/es6-super.js
tests/get-declared-variables.js
tests/implied-strict.js
tests/nodejs-scope.js
tests/references.js
tests/typescript.js

This PR updates some outdated dependencies. I have also run the autofixer and will comment on places I manually changed things.
I haven't worked in this repository very much, so I'd really love feedback/reviews from others! I'm specifically unsure of the TypeScript change (though I think what I have here makes sense?).
~CI is failing in Node <=6 because we've dropped support in ESLint v6. Should we also drop support and do a major release of `eslint-scope`?~
~__Edit:__ PR can be found [here](https://github.com/eslint/eslint-scope/pull/54).~
~__Edit 2:__ As mentioned in https://github.com/eslint/eslint-scope/pull/54, Webpack relies on this package directly and still supports Node@6. Maybe we want to keep support for Node 6 (and just drop support for Node 4)? We won't be able to upgrade to …

Upgrade: update dependencies after dropping support for Node <8

---

package.json

Updated esrecurse version to support latest estraverse with optional chaining support
https://github.com/estools/esrecurse/pull/22

Updated `esrecurse` to ^4.3.0

---

README.md

Docs: Add range to espree options in README (fixes #66)

---

package.json

This will help reduce the install size of eslint since both `esrecurse` and `esquery` already have a dependency on estraverse 5.
The only breaking change in estraverse 5 is the removal of the version property: https://github.com/estools/estraverse/commit/f522cbe05b1e71ba8243232012f86e00b4d8b06a
This can safely go out as a patch release.

Upgrade: estraverse to version 5

---

lib/index.js
lib/scope-manager.js
tests/nodejs-scope.js

Adds `sourceType:commonjs` support so that passing this option is equivalent to setting `nodejsScope: true`.
Related: https://github.com/eslint/espree/pull/520

feat: Add sourceType:commonjs support

---

tests/es6-block-scope.js
tests/es6-import.js
tests/es6-iteration-scope.js
tests/es6-switch.js
tests/implied-strict.js
tests/util/ecma-version.js

test: add tests with year-based `ecmaVersion`

---

.github/workflows/ci.yml

ci: use node v16 for `Lint` job

---

lib/scope.js
tests/use-strict.js

Fixes https://github.com/eslint/eslint-scope/issues/86 by setting `Scope#isStrict` to `false` on all scopes if `ecmaVersion < 5`.

fix: ignore `"use strict"` directives in ES3

---

lib/referencer.js
lib/scope-manager.js
tests/nodejs-scope.js

Renames the private __isNodejsScope to isGlobalReturn to formally make it part of the interface and available in ESLint.
I chose `isGlobalReturn` instead of `isNodejsScope` because the [typescript-eslint scope manager](https://github.com/typescript-eslint/typescript-eslint/blob/a4b633b9ab106e5889c2372c018b1b937ff0afbb/packages/scope-manager/src/ScopeManager.ts#L69-L71) already exposes a method called `isGlobalReturn`, so copying that would ensure that the most popular alternative scope manager already has the same method.
Refs eslint/eslint#16999

feat: Add isGlobalReturn method on scopeManager

---

.github/workflows/ci.yml
package.json

feat!: Require Node.js ^18.18.0 || ^20.9.0 || >=21.1.0

---

lib/referencer.js
tests/es6-class.js
tests/es6-super.js

Fixes #59
Updates `Referencer#visitClass()` to visit `node.superClass` after the class scope is nested, and after the class name variable is defined if it exists.
This means that `extends` is evaluated in the class scope, as the ECMAScript Specification defines.

fix!: class `extends` is evaluated in the class scope

---

lib/index.js
lib/scope-manager.js
lib/scope.js
tests/use-strict.js

Fixes #117
Updates the code that searches for `"use strict"` directives to use the [`directive` property](https://github.com/estree/estree/blob/master/es5.md#directive) as the only way to determine whether a node represents a directive. All other ways are dropped, as it is expected that the given AST follows the ESTree Spec.
Option `directive` that was enabling the use of non-standard DirectiveStatement nodes is also dropped.
The `("use strict");` test demonstrates the behavior change. The other tests are added as regression tests, they were already passing before this change.

feat!: use ESTree `directive` property when searching for `"use strict"`

---

README.md

This PR adds a "Security Policy" section to the readme file, like those in the [eslint](https://github.com/eslint/eslint/blob/5251327711a2d7083e3c629cb8e48d9d1e809add/README.md?plain=1#L160-L162) and [espree](https://github.com/eslint/espree/blob/b0767ef7ba6979a1005c93c49c41aff1af483e07/README.md?plain=1#L180-L182) repos.
Tidelift recommends [creating a discoverable security policy](https://support.tidelift.com/hc/en-us/articles/11781961573012-Create-a-discoverable-security-policy) for registered packages. Once we have added the relevant information and the link to the readme file, we will be able to set the readme file as a discoverable security policy for eslint-scope in Tidelift. eslint and espree already have this setting.

docs: document Security Policy

---

lib/referencer.js
tests/catch-scope.js

Refs https://github.com/eslint/eslint/pull/18636#pullrequestreview-2150587740
Currently, if catch param is a pattern, `Definition#name` of variables created in the pattern points to the pattern instead of the Identifier nodes.
Repro:
```js
import * as eslintScope from 'eslint-scope';
import * as espree from 'espree';
const code = "try {} catch({ message }) {}";
const ast = espree.parse(code, { range: true, ecmaVersion: 2015 });
const scopeManager = eslintScope.analyze(ast, { ecmaVersion: 2015 });
const catchScope = scopeManager.scopes[2];
const variable = catchScope.variables[0];
console.log(variable.name); // "message"
console.log(variable.defs[0].name.type); // "ObjectPattern" !
```
This fixes the mentioned Definitions to point to Identifier nodes.
I've verified that all tests in …

fix: `Definition#name` in catch patterns should be `Identifier` node
